### ISSUE TITLE
Cannot access index.php

### ISSUE THREAD

**Issue by borovez** [adhocore/docker-lemp#21]
Hi,

I am new to docker, but I have successfully setup this container and I see the following page when I visit localhost:8080
![image](https://user-images.githubusercontent.com/1531030/93397681-17de4d80-f848-11ea-817f-589174c68ecd.png)

I cannot figure out how to redirect this page to my index.php... 

I have a docker-compose.yml file in my laravel project like so:

```
# ./docker-compose.yml
version: '3'

services:
  app:
    image: adhocore/lemp:7.4
    # For different app you can use different names. (eg: )
    container_name: testapp
    volumes:
      - db_data:/var/lib/mysql
      # Here you can also volume php ini settings
      # - /path/to/zz-overrides:/usr/local/etc/php/conf.d/zz-overrides.ini
    ports:
      - 8080:80
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: testapp
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
      # for postgres you can pass in similar env as for mysql but with PGSQL_ prefix

volumes:
  db_data: {}
```

My project folder structure is:
![image](https://user-images.githubusercontent.com/1531030/93397829-655aba80-f848-11ea-9065-f4e388192ffa.png)
