### ISSUE TITLE
Unable to connect to MYSQL

### ISSUE THREAD

**Issue by borovez** [adhocore/docker-lemp#22]
Hello,

I am unable to connect to the MYSQL server when trying to migrate for example in my Laravel application.
I can connect to MYSQL through the container CLI using the same credentials.

Also, a secondary issue is Mailcatcher, there is nothing when I try to reach http://localhost:8888/ (localhost refused connection)

.env
```
DB_CONNECTION=mysql
DB_HOST=127.0.0.1
DB_PORT=3306
DB_DATABASE=app
DB_USERNAME=admin
DB_PASSWORD=password
```

docker-compose.yml
```
version: '3'

services:
  app:
    image: adhocore/lemp:7.4
    container_name: app
    volumes:
      - db_data:/var/lib/mysql
      - .:/var/www/html
    ports:
      - 8080:80
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: app
      MYSQL_USER: admin
      MYSQL_PASSWORD: password

volumes:
  db_data: {}
```

Connecting to MYSQL via container CLI using same credentials:

![image](https://user-images.githubusercontent.com/1531030/93716173-37bd8c00-fb3c-11ea-8494-56317620b6ef.png)

Error running migrate:
> $ php artisan migrate
>
> Illuminate\Database\QueryException 
>  SQLSTATE[HY000] [2002] Connection refused (SQL: select * from information_schema.tables where table_schema = app and table_name = migrations and table_type = 'BASE TABLE')
